CREATE TABLE [USER] (
    ID INT IDENTITY(1,1) NOT NULL,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    EMAIL VARCHAR(20),
    PASSWORD VARCHAR(256), 
    PRIMARY KEY (ID),
    CONSTRAINT UQ_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE FLIGHT (
    ID INT IDENTITY(1,1) NOT NULL,
    FLIGHT_NUMBER VARCHAR(20) NOT NULL,
    OPERATING_AIRLINES VARCHAR(20) NOT NULL,
    DEPARTURE_CITY VARCHAR(20) NOT NULL,
    ARRIVAL_CITY VARCHAR(20) NOT NULL,
    DATE_OF_DEPARTURE DATE NOT NULL,
    ESTIMATED_DEPARTURE_TIME DATETIME2 DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE PASSENGER (
    ID INT IDENTITY(1,1) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    MIDDLE_NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    PHONE VARCHAR(10),
    PRIMARY KEY (ID)
);

CREATE TABLE RESERVATION (
    ID INT IDENTITY(1,1) NOT NULL,
    CHECKED_IN TINYINT,
    NUMBER_OF_BAGS INT,
    PASSENGER_ID INT,
    FLIGHT_ID INT,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(ID) ON DELETE CASCADE,
    FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(ID)
);

CREATE TABLE ROLE (
    ID INT IDENTITY(1,1) NOT NULL,
    NAME VARCHAR(20),
    PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLE (
    USER_ID INT,
    ROLE_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES [USER](ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

-- Insert into ROLE table
INSERT INTO ROLE (ID, NAME) VALUES (1, 'ROLE_ADMIN');

-- Insert into USER_ROLE table
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);


